version: '2'
services:
  db:
    extends:
      file: common.yml
      service: db
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    extends:
      file: common.yml
      service: web
    command: sh -c "rm /myapp/tmp/pids/server.pid; rails s -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db

volumes:
  mysql_data:
