version: '2'

services:
  db:
    extends:
      file: common.yml
      service: db
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    extends:
      file: common.yml
      service: web
    command: sh -c "rm -f /myapp/tmp/pids/server.pid; rails server"
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    links:
      - db
    environment:
      - MYSQL_HOST=db

volumes:
  mysql_data:
